[package]
name = "toy-turn"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
bytes = "1.7"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
rand = "0.8"
hmac = "0.12"
sha1 = "0.10"
crc32fast = "1.4"

[dev-dependencies]
hex = "0.4"
